#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Jul 25 11:37:13 CEST 2023
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 1b91929911e948f7b5b2ab779e43abb2 --incr --debug typical --relax --mt 8 -L MFclock -L secureip --snapshot dcf_tb_behav MFclock.dcf_tb -log elaborate.log"
xelab -wto 1b91929911e948f7b5b2ab779e43abb2 --incr --debug typical --relax --mt 8 -L MFclock -L secureip --snapshot dcf_tb_behav MFclock.dcf_tb -log elaborate.log

